services:
# create nginx container
# copy all .html, .php and .css files to /usr/share/nginx/html
# map port 8080 on host to port 80 on container
# restart container always
# using config file in ./html/nginx.conf
    web:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./html:/usr/share/nginx/html
            - ./html/nginx.conf:/etc/nginx/nginx.conf
        restart: always

    db:
        image: mysql
        restart: always
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: system-3@1357
            MYSQL_USER: user
            MYSQL_PASSWORD: pass-away

# create nodejs container for running nodejs app
# copy all files in ./backend to /usr/src/app
# map port 3000 on host to port 3000 on container
# using node:22 image
# running after db container
    nodejs:
        build: ./backend/  # Build the Dockerfile in the current directory
        ports:
            - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
        environment:
            DB_HOST: db  # Define the database host as the service name
            DB_USER: root
            DB_PASSWORD: system-3@1357
            DB_NAME: schedule